from . import views
from django.urls import path
from . models import *

urlpatterns = [
    path('indexShop',views.indexShop,name='indexShop'),
    path('regShop',views.regShop,name='regShop'),
    path('Viewregister',views.Viewregister,name='Viewregister'),
    path('',views.loginShop,name='loginShop'),
    path('Viewlogin',views.Viewlogin,name='Viewlogin'),
    path('Viewlogout',views.Viewlogout,name='Viewlogout'),
    path('review',views.review,name='review'),
    path('re_view',views.re_view,name='re_view'),
    path('About',views.About,name='About'),
    path('Shopcart',views.Shopcart,name='Shopcart'),
    path('shop_cart/<int:kpid>/',views.shop_cart,name='shop_cart'),
    path('checkoutp',views.checkoutp,name='checkoutp'),
    path('S_check',views.S_check,name='S_check'),
    path('tchecktable',views.tchecktable,name='tchecktable'),
    path('check_delete/<int:cdid>/',views.check_delete,name='check_delete'),
    path('shopcheck',views.shopcheck,name='shopcheck'),
    path('cart_update',views.cart_update,name='cart_update'),
    path('Shop_delete/<int:did>/',views.Shop_delete,name='Shop_delete'),
    path('ShopcartG',views.ShopcartG,name='ShopcartG'),
    path('shop_cart_G/<int:gpid>/',views.shop_cart_G,name='shop_cart_G'),
    path('cart_update_G',views.cart_update_G,name='cart_update_G'),
    path('Shop_delete_G/<int:Gdid>/',views.Shop_delete_G,name='Shop_delete_G'),
    path('ShopcartL',views.ShopcartL,name='ShopcartL'),
    path('shop_cart_L/<int:lpid>/',views.shop_cart_L,name='shop_cart_L'),
    path('cart_update_L',views.cart_update_L,name='cart_update_L'),
    path('Shop_delete_L/<int:Ldid>/',views.Shop_delete_L,name='Shop_delete_L'),
    path('ladiesproduct0/<str:category>/',views.ladiesproduct0,name='ladiesproduct0'),
    path('ladiessinglepro/<int:lid>/',views.ladiessinglepro,name='ladiessinglepro'),
    path('gentsproduct1/<str:categ>/',views.gentsproduct1,name='gentsproduct1'),
    path('gentssinglepro/<int:gid>/',views.gentssinglepro,name='gentssinglepro'),
    path('kidsproduct2/<str:cat>/',views.kidsproduct2,name='kidsproduct2'),
    path('kidssinglepro/<int:kid>/',views.kidssinglepro,name='kidssinglepro'),
    path('adminIndexShop',views.adminIndexShop,name='adminIndexShop'),
    path('Bgents',views.Bgents,name='Bgents'),
    path('display_brands',views.display_brands,name='display_brands'),
    path('gbedit/<int:bid>/',views.gbedit,name='gbedit'),
    path('gbupdate/<int:gbid>/',views.gbupdate,name='gbupdate'),
    path('gbdelete/<int:gbdid>/',views.gbdelete,name='gbdelete'),
    path('gbtable',views.gbtable,name='gbtable'),
    path('Progents',views.Progents,name='Progents'),
    path('display_products',views.display_products,name='display_products'),
    path('gpedit/<int:pid>/',views.gpedit,name='gpedit'),
    path('gpupdate/<int:gpid>/',views.gpupdate,name='gpupdate'),
    path('gpdelete/<int:gpdid>/',views.gpdelete,name='gpdelete'),
    path('gptable',views.gptable,name='gptable'),
    path('Bladies',views.Bladies,name='Bladies'),
    path('addbrands',views.addbrands,name='addbrands'),
    path('LadiesBrandtable',views.LadiesBrandtable,name='LadiesBrandtable'),
    path('Lbrandedit/<int:Lid>/',views.Lbrandedit,name='Lbrandedit'),
    path('Lbrandupdate/<int:Luid>/',views.Lbrandupdate,name='Lbrandupdate'),
    path('Lbranddelete/<int:Ldid>/',views.Lbranddelete,name='Lbranddelete'),
    path('lpro',views.lpro,name='lpro'),
    path('ladiespro',views.ladiespro,name='ladiespro'),
    path('protable',views.protable,name='protable'),
    path('p_edit/<int:pe_id>/',views.p_edit,name='p_edit'),
    path('p_update/<int:up>/',views.p_update,name='p_update'),
    path('p_delete/<int:dd>/',views.p_delete,name='p_delete'),
    path('kids',views.kids,name='kids'),
    path('scart',views.scart,name='scart'),
    path('BKtables',views.BKtables,name='BKtables'),
    path('edits/<int:seid>',views.edits,name='edits'),
    path('editsc/<int:supid>',views.editsc,name='editsc'),
    path('kdelete/<int:sdid>',views.kdelete, name='kdelete'),
    path('kproduct',views.kproduct,name='kproduct'),
    path('psart',views.psart,name='psart'),
    path('ptables',views.ptables,name='ptables'),
    path('pedits/<int:pid>',views.pedits,name='pedits'),
    path('tchecktable1',views.tchecktable1,name='tchecktable1'),
    path('peditsc/<int:pid>',views.peditsc,name='peditsc'),
    path('tchecktable2',views.tchecktable2,name='tchecktable2'),
    path('pma12',views.pma12,name='pma12'),
    path('pdelete/<int:pid>',views.pdelete, name='pdelete'),
    path('sklog', views.shopkeeper, name='idcheck'),
    path('skcheck/', views.shopkeepercheck, name='skcheck'),
    path('users/', views.usertable, name='users'),



]