# Generated by Django 4.0 on 2022-06-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_shop_app', '0003_rename_email_userreg_comfirm_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=200, null=True)),
                ('bdes', models.TextField(max_length=500, null=True)),
                ('bimg', models.ImageField(null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='brandladies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='scdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
