# Generated by Django 4.0 on 2022-06-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_shop_app', '0004_brand_brandladies_scdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandladies',
            old_name='Description',
            new_name='description',
        ),
    ]
