# Generated by Django 4.0 on 2022-06-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_shop_app', '0006_rename_bimg_brand_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='lpro_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('categorie', models.CharField(max_length=200, null=True)),
                ('product_description', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='pdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=25, null=True)),
                ('category', models.CharField(max_length=25, null=True)),
                ('pdescription', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('size', models.CharField(max_length=25, null=True)),
                ('file2', models.ImageField(null=True, upload_to='picture/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200, null=True)),
                ('brname', models.CharField(max_length=200, null=True)),
                ('pdes', models.TextField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('pimg', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
