# Generated by Django 4.0 on 2022-06-26 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_shop_app', '0008_shopcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='E_shop_app.shopcart')),
            ],
        ),
    ]
