# Generated by Django 4.0 on 2022-07-01 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_shop_app', '0011_shopcartg_lproductid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcartl',
            name='Lproductid',
        ),
        migrations.RemoveField(
            model_name='shopcartl',
            name='userid',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='Gproductid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='E_shop_app.product'),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='Lproductid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='E_shop_app.lpro_db'),
        ),
        migrations.DeleteModel(
            name='shopCartG',
        ),
        migrations.DeleteModel(
            name='shopCartL',
        ),
    ]
