# Generated by Django 4.0 on 2022-07-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_shop_app', '0012_remove_shopcartl_lproductid_remove_shopcartl_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcheckout',
            name='address1',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopcheckout',
            name='address2',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopcheckout',
            name='c_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopcheckout',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shopcheckout',
            name='fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopcheckout',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopcheckout',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shopcheckout',
            name='order_place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopcheckout',
            name='post',
            field=models.IntegerField(null=True),
        ),
    ]
